- src/Field.js
- src/Field.test.js
Fixed this warning:
```
Warning: The `value` prop supplied to <select> must be an array if `multiple` is true.
Check the render method of `Field`.
```
> Fixed multiple select issue

- README.md
- src/ReactFinalForm.js
- src/types.js.flow
Oops. Left out a `initialize()` and left `reset()` out of the docs. Fixed.
> Added missing initialize prop to FormRenderProps

- .github/CONTRIBUTING.md
Found when doing erikras/react-final-form-arrays#1 🙂
> Fix package naming

- src/ReactFinalForm.js
- src/ReactFinalForm.test.js
> Returned a promise from handleSubmit when submission is async

- src/Field.js
Addresses confusion of devs wanting to set a field value with the `value` prop.
> Added warning on improper value prop usage

- README.md
- package.json
- src/ReactFinalForm.js
- src/ReactFinalForm.test.js
- src/types.js.flow
Support for decorators, from [🏁 Final Form `v1.3.0`](https://github.com/final-form/final-form/releases/tag/v1.3.0).
> Added decorator support

- src/renderComponent.js
- src/renderComponent.test.js
> Pass render prop when component is used

- package.json
- src/ReactFinalForm.js
- src/index.d.ts
- src/types.js.flow
> Fix up for Api -> FormApi rename, and actually expose TypeScript typings

- src/Field.js
- src/Field.test.js
- src/ReactFinalForm.test.js
- src/index.d.ts
- src/types.js.flow
The "value lifecycle" from Redux Form was a must-have feature for me and others (see #45 ). This PR introduces three new props for the `Field` component:
- `format: (value: ?any, name: string) => ?any | null`
- `parse: (value: ?any, name: string) => ?any | null`
- `normalize: (value: ?any, previousValue: ?any, allValues: object) => ?any`
They work basically the same way as they do in Redux Form. The `allowNull` prop is still respected and applied after `format`. By default, `format` converts undefined to an empty string and `parse` converts an empty string to undefined. Either can be set to `null` explicitly opt-out of that behavior and of course a custom function can be provided for more advanced cases.
The `normalize` function is almost the same except it is not passed the …
> Value Lifecycle Props

- src/index.d.ts
The first commit includes a fix for #79.
In the second commit I included the type of the props of the component field, which allows us to write:
```ts
const InputAdapter = ({input, ...rest}: FieldRenderProps) => {
return (
<input {...input} {...rest}/>
);
};
```
Without typescript complaining about not knowing `input` or `meta` props.
This makes the third party component example compile.
In the third commit, I added string as a legal value for `component` to match the basic example:
```ts
<Field
name="firstName"
component="input"
/>
```
> typescript types fixes

- src/index.d.ts
Follow-on to/depends on https://github.com/final-form/final-form/pull/54
When a developer wants to reuse types, one cannot pick from or extend any `type`, but can from any `interface`.
This PR is neutral in typing results but provides a better case for reuse/extension of types in a developer's application.
> [typescript] Use interfaces where possible for reuse cases

- package.json
- src/Field.js
- src/Field.test.js
> Render custom checkbox and custom radio with checked prop

- src/index.d.ts
- src/types.js.flow
It's unlikely that the errors will ever be a boolean. Typically they are `null | string` but final-form supports `any` value.
> Make errors `any` not `boolean`

- src/index.d.ts
These methods already appear in SubsetFormApi
> Remove duplicated methods from FormRenderProps

- src/index.d.ts
> RenderableProps component prop should still be given T

- src/Field.js
- src/Field.test.js
- src/FormSpy.js
- src/FormSpy.test.js
- src/ReactFinalForm.js
Fixes #150.
It did require changing some tests because some of the components rendered more often than before, but this is still the right move for all the reasons described in #150.
> Stopped extending React.PureComponent

- src/Field.js
- src/Field.test.js
There were times when it could be `-1` or `0` instead of `true` or `false`.
> Ensured that input.checked is boolean

- src/Field.test.js
- src/FormSpy.test.js
- src/ReactFinalForm.js
- src/ReactFinalForm.test.js
> Fixed warning with server-side rendering

- package-lock.json
- package.json
Jest 22 comes with JSDOM 11 which has raf natively
> chore: remove unnecessary raf polyfill

- src/ReactFinalForm.js
- src/ReactFinalForm.test.js
[closes #128]
The peer dependency on final-form will need to be updated to the version that includes the `setConfig` method.
> Handle props changes

- src/Field.js
Adds `meta.data` back as it is listed as non-optional in the readme. 
Although it is flagged as optional in `final-form` it is always initialized with an object literal.
Updating to the newest `react-final-form` version also breaks the setFieldData-example: https://codesandbox.io/s/lrq5j4r8vl
> Fix regression: meta.data

- .travis.yml
semantic-release is not used on Travis CI builds so it is not neeeded to install it.
> chore: do not install semantic-release on CI

- README.md
May be useful to someone trying to use the `AsyncTypeahead` along with `redux` and `react-final-form`. I am quite happy with this solution. Also, as far as I am concerned, this closes https://github.com/final-form/final-form/issues/122
> Add AsyncTypeahead and Redux example

- package-lock.json
- package.json
- src/Field.js
- src/FormSpy.js
- src/ReactFinalForm.js
- src/ReactFinalForm.test.js
Also adds `UNSAFE_` prefixes to fix #267.
Includes `react-lifecycles-compat` as described [on the React blog](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#open-source-project-maintainers).
> Changed to not require RFF update when new FF config props are added

- src/Field.js
- src/FormSpy.js
- src/ReactFinalForm.js
Fixes oversight from #272.
Installed in accordance with [instructions on React Blog](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#open-source-project-maintainers).
> Actually use react-lifecycles-compat polyfill

- src/ReactFinalForm.js
If you have two nested forms, both forms onSubmit were called because stopPropagation wasn't called. With this fix in place, it looks like nested forms are working properly.
Fixes #276.
> Fix support for nested forms by calling stopPropagation

- src/ReactFinalForm.js
- src/ReactFinalForm.test.js
This fixes a bug where re-rendering a form with a new `initialValues` object would reset all field values, even if the new `initialValues` were shallowly equal to the old ones. See the new test for an example of this.
This did cause a concerning change to another test, which was expecting `validate` to be called twice, but now it's only caused once. I think the latter behavior is actually correct and the test was written to work around this bug, but would appreciate some extra eyes on that test change to confirm.
> Don't call setConfig for initialValues

- .github/CONTRIBUTING.md
- src/ReactFinalForm.test.js
The test coverage was so close to 100% 
```
[test] ---------------------|----------|----------|----------|----------|-------------------|
[test] File                 |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
[test] ---------------------|----------|----------|----------|----------|-------------------|
[test] All files            |      100 |    98.97 |      100 |      100 |                   |
[test]  Field.js            |      100 |      100 |      100 |      100 |                   |
[test]  FormSpy.js          |      100 |      100 |      100 |      100 |                   |
[test]  ReactFinalForm.js   |      100 |    95.65 |      100 |      100 |           106,109 |
[test]  diffSubscription.js |      100 |      100 |      100 |      100 |                   | …
```
> [ReactFinalForm.js]: Add a test for 100% test coverage

- package.json
To make the postinstall script work.
Commit 802eb474a82004deadf544a65409c127c048b282 added a reference to scripts/postinstall.js. However, the scripts array in package.json does not include the scripts folder which makes the script not available in the NPM package.
This leads to the following error:
```
$ npm install react-final-form
> react-final-form@3.6.6 postinstall .....\node_modules\react-final-form
> node ./scripts/postinstall.js || exit 0
internal/modules/cjs/loader.js:583
throw err;
^
Error: Cannot find module '.....\node_modules\react-final-form\scripts\postinstall.js'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
at Function.Module._load (internal/modules/cjs/loader.js:507:25)
at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
at …
```
> Add scripts folder to NPM package

- docs/faq.md
Code example in the FAQ now matches the code in the CodeSandbox example.
Using the code in the FAQ document before this change introduced an issue in Firefox addressed in: https://github.com/final-form/react-final-form/issues/181
> Fix FAQ external submit via document.getElementById() code example

- README.md
- src/Field.js
- src/index.d.ts
- src/types.js.flow
This was present in redux-form but not in final-form. See final-form/final-form#172
Depends on final-form/final-form#173
> Add `meta.submitting` to FieldRenderProps

- src/Field.js
- src/FormSpy.js
- src/ReactFinalForm.js
- src/index.d.ts
- src/index.js
- src/index.js.flow
- src/reactFinalFormContext.js
- src/reactFinalFormContext.test.js
- src/types.js.flow
I think it is good to migrate to new recommended Context API. There is also some library to integrate like `react-final-form-arrays`. I will also create PRs for them
> Migrate to new React Context API

- src/reactFinalFormContext.js
- src/reactFinalFormContext.test.js
Since `4.0.0` the displayName of `Field` and `FormSpy` is broken, what causes some issues, for example with `Jest` snapshot tests (see attached screenshots). This PR fixes the displayName of said components.
Before:
After:
> Fix displayName of context provider HOC

- README.md
- src/index.d.ts
final-form#368 updated the README with the updated prototype for FieldProps.validate.
This change makes the associated update to the Typescript types.
> Update FieldProps.validate type definition

- README.md
The updated codesandbox can be found under https://codesandbox.io/s/3190284lv5. Since @erikras is the owner of the original codesandbox he would have to pull in changes.
- some props were moved from the root to `inputProps`
- `InputProps` -> `inputProps` for the selection controls
- `!!checked` -> `Boolean(checked)` (clearer intent)
Closes #362
> Updated material-ui demo

- src/index.d.ts
This is where the third argument of the `validate` function has been added: https://github.com/final-form/final-form/pull/125
But no Typescript typings were added.
Fixed.
Also, I've moved `meta` typings into separate `type`, to avoid typings duplication.
> Add Typescript typings for the third argument of the `validate` function

- src/ReactFinalForm.d.test.tsx
- src/index.d.ts
- src/index.js
- tslint.json
The only current way to use the react context is via the HOC. This exposes it in index and adds typescript tests for all forms of use, including commented test for React 16.6 use.
> Expose react context from index, added typescript tests, prepare for React 16.6

- typescript/index.d.ts
Hi!
The Flow type signature of `input.onChange` is [`(event: SyntheticInputEvent<*> | any) => void`](https://github.com/final-form/react-final-form/blob/master/src/Field.js#L117) while the TypeScript signature is [`onChange: (event: React.ChangeEvent<T>) => void`](https://github.com/final-form/react-final-form/blob/master/typescript/index.d.ts#L25).
This PR adds the `| any` in the TS definition.
> Fix input.onChange TS type signature

- src/ReactFinalForm.js
- src/flattenSubscription.js
- src/flattenSubscription.test.js
- src/useField.js
- src/useFormState.js
The simplest thing I could think of that would make flattenSubscription hooks-safe.
> Make flattenSubscription hooks-safe

- src/useField.js
First off, I love the project and appreciate being able to use it.
In my project I have what may be an unconventional form where the fields that are rendered on the screen depend on what the user selects. The form as well as all the selectable categories are visible at the same time.  I found a problem when I was migrating to version 5.x in my unit tests where once a subset was 'selected' a second time a textarea onChange event no longer updated the fields value. 
I was trying to debug my own code and found no problems so I started playing with the code under the hood and I found that `state.change` was not part of the dependencies of the onChange useCallback. I added it and my test started passing as expected. 
Adding state.change as a dependency is all the pull request does, but if …
> Bug Fix: Add state.change to useField's onChange dependencies.

- typescript/index.d.ts
add `afterSubmit` and `beforeSubmit` callbacks to the Typescript definition file.
> add beforeSubmit and afterSubmit to typescript def

- src/ReactFinalForm.js
fixes #487
Previously, when it was checking in the subscribe func if state updated https://github.com/final-form/react-final-form/blob/4ca1ce7a7800c08b249219e14740ec2c1ed7e222/src/ReactFinalForm.js#L89  the current state `state` - was always the initial state, bec of js closures.
So, the `submitting` state got set to `true` bec that was different than the initial state but when attempting to set back to false.. it was checking the initial state of `false` with current updated state of `false` and it was equal and therefore did not update and reset state.
Changed to add `state` to the `useEffect` deps so it will rerun the effect, causing it to create a new subscribe func with the updated state.
fixes #492
> Fix `submitting` state never getting reset

- typescript/index.d.ts
`useField` has a [default value](https://github.com/final-form/react-final-form/blob/master/src/useField.js#L39) but the Types do not.
That means `useField('name')` throws an error in TS.
This PR make the options object optional.
> Update Types to make useField's options optional

- src/types.js.flow
There was a mismatch between the source code and Flow typings which led to the following error:
```js
<Field
name={name}
component={SomeCustomInputComponent}
/* ^^^ Flow error here:
Cannot create Field element because in property component:
• Either function [1] is incompatible with string literal
input [2].
• Or function [1] is incompatible with string literal
select [3].
• Or function [1] is incompatible with string literal
textarea [4].
*/
/>
```
> Fix Flow typings for UseFieldConfig and FieldProps

- package-lock.json
- package.json
- src/FormSpy.js
- src/ReactFinalForm.js
- src/context.js
- src/getContext.js
- src/index.js
- src/index.js.flow
- src/types.js.flow
- src/useField.js
- src/useForm.js
- src/useFormState.js
- typescript/index.d.ts
Depends on https://github.com/final-form/final-form/pull/223.
> Strongly typed form values for Flow and Typescript

- src/ReactFinalForm.js
- src/ReactFinalForm.test.js
- src/types.js.flow
- typescript/index.d.ts
[Suggested in a tweet](https://twitter.com/Syynth/status/1138204720974241792)
> @erikras do you have any interest in allowing the React bindings for @finalformjs to receive the FormApi instance as a prop? I'm interested in it for testing purposes but I could imagine it also having value if someone wanted to pass a custom FF compatible API impl.
It took me a minute to understand what was being asked, but when I did, it seemed like a pretty cool idea. Just as Final Form doesn't mind what view framework consumes it, React Final Form shouldn't mind what underlying engine that comports to the Final Form API is being used.
> Allowed swappable final-form APIs

- typescript/index.d.ts
By default FormValues is of type `object` which is empty. When accessing a property on the values object, TypeScript raises the following error:
`Property 'myprop' does not exist on type 'object'.ts(2339)`
This PR resolves this issue.
> Replace empty object default type with any object

- typescript/Field.test.tsx
- typescript/index.d.ts
Follow-up to #522, which didn't completely get the JSX generics all the way to the `Field` value.
> Strongly typed field values

- README.md
Very small pull request that updates the docs to reflect the actual Flow types of `handleSubmit`.
I think some explanation may be added, though. If the function is intended to be passed to the `<form>` element, one might wonder what is the point of returning a promise.
> Actual return type for the handleSubmit function

- src/Field.test.js
- src/useField.js
When there's a `format` function that's called `onBlur` it passes the
current value from state to that `format` function.
https://github.com/final-form/react-final-form/blob/41d24d6db197a5eec73e52623a267f98bb2337dc/src/Field.js#L113
This causes that when the field's `onChange` is called from within the `onBlur`
the `formatOnBlur` function is not getting the updated value.
Rather, it has the previous value passed to it, so when
formatting the value it ends up formatting and returning the previous value.
This pr changes to pass the current updated value from `props.reactFinalForm`'s state,
to the format func so it always gets the current value.
[See Demo](https://codesandbox.io/s/j2j8w0nlp5)
> Use updated value for `formatOnBlur` format func

- package-lock.json
- package.json
- src/ReactFinalForm.js
- src/ReactFinalForm.test.js
- src/useField.js
Fixes #523, ~~**_but only for initial fields_**~~.
~~Because our fields have to register twice on first render, the `destroyOnUnregister` will naturally destroy the value on first render. This PR fixes the bug for fields that are present on first form render, but will not fix it for new ones added.~~
**Update**: Works now for all fields, regardless of when they are added.
> Fixed destroyOnUnregister bug

- README.md
- package-lock.json
- package.json
- src/Field.test.js
- src/useField.js
Support for `final-form` [`v4.16.0`](https://github.com/final-form/final-form/releases/tag/v4.16.0)'s `validating` flag in the `meta` object.
> Validating flag support

- src/Field.test.js
- src/useField.js
Some custom widgets (such as the SingleDatePicker in react-dates) have very strict prop types, that reject unknown props. So even `type={undefined}` will fail the prop type check.
With this PR `type` is only included in `input`, if it's not undefined.
> Do not pass undefined type to input

- typescript/index.d.ts
This PR for resolve [issue #175](https://github.com/final-form/react-final-form/issues/175)
Now u can add any additional props to your custom component. I use custom Select, so i need to pass label, options and anyAdditionalProp.
**RenderForm.tsx**
```
<Field<string>
name="stack"
component={SelectAdapter}
label="Tools"
options={optionsArrayVariable}
anyAdditionalProp={anyAdditionalProp}
/>
```
**FormAdapters.tsx (contain adapters for custom components)**
```
interface SelectAdapterProps extends HTMLElement {
label?: string;
options: Option[];
anyAdditionalProp: any;
}
export const SelectAdapter = (props: FieldRenderProps<string, SelectAdapterProps>) => {
const {
input,
meta,
...rest
} = props;
const {
options,
label,
anyAdditionalProp,
} = input;
return (
<Select
options={options} …
```
> Issue 175: pass any additional props to custom component

- typescript/index.d.ts
Allows providing a shape for `FieldRenderProps`.
> Allow typed render props in TS

- src/ReactFinalForm.js
I know that with classes this should go in `componentWillUnmount()`, but I'm not 100% clear on the semantics of `useEffect()`. Does it also run parent-first when a tree is being unmounted?
If this does what I expect it to, will fix #408. Will make a test case before removing the RFC tag.
> RFC: pausing validation before unmount

- typescript/index.d.ts
The current typings depend upon `Omit<>` from ts-essentials but this is a common type that has been added by people (myself included) to their projects. The duplicate definition of `Omit<>` causes the compiler to complain. `Omit<>` has also been [added to TS 3.5](https://devblogs.microsoft.com/typescript/announcing-typescript-3-5/#the-omit-helper-type) so this will cause a conflict for those people who are targeting 3.5
To work around this I have changed the use of the` Omit<>` type helper and replaced it with the more explicit use of `Pick<>` and `Exclude<>`. This will prevent anyone that has their own Omit<> type or is targeting TS 3.5 from failing to build the project. 
The added bonus is that ts-essentials is no longer needed so there is one less dependency required :smiley_cat:. …
> removes Omit from the typescript definitions

- src/Field.js
- src/FormSpy.js
- src/ReactFinalForm.js
- src/getters.js
- src/renderComponent.js
- src/renderComponent.test.js
- src/types.js.flow
- src/useField.js
- src/useField.test.js
- src/useFormState.js
Has the added benefit of making all the state values readonly.
That should only be a breaking change for the naughtiest of users.
> Lazy evaluation of form and field state

- src/Field.test.js
- src/useField.js
fixes #517
The same thing still happens for defaultValue & initialValue - but to fix those you'd have to decide what should happen when they change (IMHO nothing should happen, only first values should get registered).
> Fix issue with inline isEqual causing an infinite rerender loop

- typescript/ReactFinalForm.test.tsx
- typescript/index.d.ts
When from values are typed (suppose `T`) and we pass some decorators, instead `Decorator<T>[]`  decorator prop's type resolves to `Decorator<object>[]`.
So correctly typed decorators with correctly typed form process type error.
> Pass FormValues type to Decorator

- typescript/index.d.ts
Similar to other occurences of default type `T extends HTMLElement = HTMLElement` in the typings file.
It is very handy to not be required to add specific HTMLElement generic if, for example, I am using custom "inputs" or if I only need to use parts of the interface that don't use the second generic.
It is actually more often that I don't need the second generic.
> Make HTMLElement generic default and optional

- typescript/index.d.ts
This PR fixes `Type 'Decorator<IValues>[]' is not assignable to type 'Decorator<object>[]'.` error when decorator is typed with signature `Decorator<IValues>`
> [ts] fix FormProps['decorators']

- typescript/index.d.ts
According to [the doc](https://final-form.org/docs/react-final-form/types/FieldProps#parse) the parse prop takes the value from the input (which is typed with `FieldValue`)
> Fix typescript typings in FieldProps

- typescript/index.d.ts
as they are actually added to props for createElement call, destructured
but then re-injected in some cases.
> Add RenderableProps to FormRenderProps

- flow-typed/npm/jest_v24.x.x.js
- src/index.js.flow
- src/useField.test.js
- src/useForm.test.js
- src/useFormState.test.js
The [exported flow typing in index.js.flow](https://github.com/final-form/react-final-form/blob/3add0f36ecc191ee1b1425142ab34b19679fa00e/src/index.js.flow#L30) doesn't match [what's actually used in `useFormState`](https://github.com/final-form/react-final-form/blob/3add0f36ecc191ee1b1425142ab34b19679fa00e/src/useFormState.js#L12). When using this externally, this causes Flow to think that `useFormState` might return `null` or `undefined`, when that appears not to be the case. It also thinks that the params are required when they're really optional.
**src/index.js.flow**
```
declare export function useFormState<FormValues>(
params: UseFormStateParams<FormValues>
): ?FormState<FormValues>
```
**src/useFormState.js**
```
function useFormState<FormValues: FormValuesShape>({
onChange, …
```
> Fix useFormState and useField Flow types

- examples/field-warnings/index.js
- examples/field-warnings/readme.md
- examples/field-warnings/warning-engine.js
see #576  and #680 
The current example does not reflect the new location of `mutators` on the `form` prop. This PR updates the code and codesandbox link.
This PR uses the updates provided by @abrad45 in #680 but src could also be copied from #576 if desired.
> Update codesandbox field-warnings example

- docs/types/FieldProps.md
👋These two links are broken in https://final-form.org/docs/react-final-form/types/FieldProps
> Fix doc links to FieldRenderProps

- typescript/index.d.ts
Use Field's first generic argument in the default for second generic argument.
Here's an example (notice any vs Date):
Since the first generic argument already defaults to any, there's no need to set any in it's place in the second generic argument. This way, if a developer only sets the first generic argument of Field, they still get the input.value prop properly typed, instead of being any (current behavior). And if they omit it all together, it'll default to any, as it currently does.
> Improved type definition for Field

- src/ReactFinalForm.js
- src/types.js.flow
- typescript/index.d.ts
Fixes #86 
The typescript typings work in my local code - in this case, with a button handler, but it should work in React Native typescript typings as well.
Let me know if the flow typings changes are fine - i did my best 😄 .
> Fix handleSubmit typings

- typescript/index.d.ts
I believe that the FieldRenderProps interface is typed incorrectly, it should actually allow `[otherProp: string]: any;`. Trying to access props other than `input` or `meta` will currently result in a Typescript error.
As shown in the docs [here](https://final-form.org/docs/react-final-form/types/FieldProps#children) arbitrary props assigned to the `Field` component are passed through to the renderProp.
```js
<Field name="myField" someArbitraryOtherProp={42}>
{props => {
console.log(props.someArbitraryOtherProp) // would print 42
return <input {...props.input}/>
}}
</Form>
```
We can see the passing of props in the `renderComponent` module here: https://github.com/final-form/react-final-form/blob/master/src/renderComponent.js#L25
Seems an issue is already raised regarding this: …
> Add otherProp to FieldRenderProps interface

- docs/examples.md
The link to the "external submit" FAQ section was not working on the docs site (https://final-form.org/docs/react-final-form/examples#external-submit). This PR fixes this by adding the link explicitly.
> Fix doc link to FAQ section about "external submit"

- package.json
Now that there's a standard way for npm to display requests for funding, that most other packages have adopted, I figured it would be a reasonable change for react-final-form as well.
> Switch to standard funding notice

- docs/types/FieldProps.md
I've noticed a wrong closing tag in the docs. This PR should fix this. 😄
> Use correct closing tag for <Field> in FieldProps.md

- .travis.yml
- package.json
- src/Field.test.js
- src/useField.js
Previously `<Field component="select" multiple>` would generate an error claiming it needs a `type="select"` prop. This was wrong, as we can just see if `component === 'select'` to know.
> Deduce select type from component prop for select-multiple

- docs/getting-started.md
- package.json
This change adds a dependency on scarf-js for installation analytics to support the maintainers of React Final Form.
Discussion from everyone is welcome! Some background on the library and the problem it's solving can be found in this post here: https://github.com/scarf-sh/scarf-js/blob/master/WHY.org. The package README (https://github.com/scarf-sh/scarf-js) has more info on exactly what data is sent on each install and how users can opt-out if they choose.
The data Scarf collects will help maintainers by keeping them informed about how the package is being used and will help drive sponsorship to support all the work that goes into React Final Form.
> Add scarf-js for anonymized installation analytics

- src/useField.js
- src/useField.test.js
If you use `useField` (or `<Field>`) and the name of the field that you subscribe to changes during the lifetime of the component, the `onFocus` handler will continue calling the `state.focus()`  function of the previous field.
The reason is that `useField` doesn't specify the `state.focus` as a dependency for `React.useCallback`.
It is a common use-case with forms that you, for example, have a list of items, and you want to be able to toggle between the active item that you are editing, but not render all the items in DOM, rather just the one you're editing. At the moment in these use-cases when switching between the active item, the `Field` does not re-mount and the handlers will not work properly.
> re-initialize onFocus/onBlur handlers if the subscribed field changes

- README.md
- package.json
Move `ts-essentials` to be a dev dependency instead of a direct dependency. By including as a dependency, the following message occurs when installing react-final-form:
```
npm ERR! peer dep missing: typescript@>=3.5.0, required by ts-essentials@3.0.5
```
Closes #682
> Move ts-essentials to be a dev dependency

- examples/auto-save-selective-debounce/AutoSave.js
The actual example of `auto-save-selective-debounce` does not work when the input is cleared.
It does only send the "save" event when the input is changed but not empty.
This is due to the fact that final-form does not send empty values in the `values` object.
> Update  auto-save-selective-debounce to handle clearing inputs

- docs/getting-started.md
- package.json
RFF version of the fix here: https://github.com/final-form/final-form/pull/361
Original issue: https://github.com/final-form/react-final-form/issues/822
> Remove scarf dep

- docs/types/FieldProps.md
Link description said `FieldRenderProps`, but link itself pointed to `FormRenderProps`.
> Fix link to FieldRenderProps in FieldProps

- docs/api/useFormState.md
useFormState returns a FormState and not a FormSpyRenderProps.
> Improve useFormState docs

- src/useField.js
Fix issues
https://github.com/final-form/react-final-form/issues/858
> Lost the formatting method call in checked field getter

- src/useField.js
- src/useField.test.js
`useField` public handlers like `onFocus`, `onChange`, `onBlur` are changing their identities based on various internal variables and externally available props/(config parts) like `value`, `name`, `parse` etc...
I am suggesting that public handlers should not be subject to identity change at all, so that consumers can rely on those without jumping through hoops with `useRef` as in https://reactjs.org/docs/hooks-faq.html#what-can-i-do-if-my-effect-dependencies-change-too-often.
As a consequence after this change consumer code relying on this behavior might break, hence this is a BREAKING CHANGE
Closes #816
> fix: stabilize useField public handler identity

- docs/api/Field.md
Just add a note for custom fields using an array, to avoid warning about initial value being a string
> Add note about using array as value

- src/ReactFinalForm.js
I am running into an issue of infinite loops when upgrading from pre-hooks code to hooks based forms.
This allows you to have something like the following where the decorators will change identity on every render, without causing that decorator to be unsubscribed and re-subscribed on every render, which seems like it could be unintentional.
I'm unsure how to write a test for this but would appreciate any guidance!
```tsx
const CustomForm = () => {
return <Form decorators={[decorator1, decorator2]} />
}
```
Tests are failing for something unrelated? `[test]     Cannot find module '@babel/plugin-transform-react-jsx-source'`
> Allow decorators prop to change identity, but not array contents, without running on every render

- src/useConstantCallback.js
- src/useConstantCallback.test.js
- src/useField.js
Further abstraction around #931.
> Use custom hook to create callback constants

- src/FormSpy.test.js
- src/ReactFinalForm.js
- typescript/Field.test.tsx
- typescript/index.d.ts
- typescript/useField.test.tsx
Sometimes it is required that in `FieldState.value` and `input.value` were of different types. This is possible through the use of the parse/format props in Field or in useField config.
But when using typescript type conversion is not performed. `input.value` is always typed as the value from FieldState
This pull request corrects the current typing.
Closes #929
> Improved typing for the ability to convert types when using parse/format

- typescript/Field.test.tsx
- typescript/index.d.ts
- typescript/useField.test.tsx
Fix typing, when using strong lint rules
Closes #946
> fix: correct input.value type for useField and Field

- src/ReactFinalForm.js
This issue is connected with this PR https://github.com/final-form/react-final-form/pull/513/files
When onSubmit returns without delay update batches and re-render never happens.
This will fix issue with `subscription` and `submitting` where `submitting` will stay `true` even thought the updated value should be `false` 
Closes [#875](https://github.com/final-form/react-final-form/issues/875), [#903](https://github.com/final-form/react-final-form/issues/903)
> fix: submitting persisting true state
