final-form/react-final-form

src/types.js.flow

Just like in erikras/final-form#2 🙂

Use $Shape<T> instead of optional fields

---

.github/CODE_OF_CONDUCT.md
.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
LICENSE

Ref: https://github.com/erikras/react-final-form/community
Just like erikras/final-form#3 🙂

Meet the GitHub community standards

---

README.md

Fix link to Asynchronous Field-Level Validation

---

src/Field.js
src/Field.test.js

Avoid api prop bleed-through

---

README.md

Fix missing jsx closing tag in doc

---

src/ReactFinalForm.js
src/ReactFinalForm.test.js

Passed along validateOnBlur to final-form

---

src/ReactFinalForm.js
src/ReactFinalForm.test.js
src/shallowEqual.js
src/shallowEqual.test.js

Allow later initialization through initialValues prop

---

src/Field.js

Stopped meta.name prop. Name is only on input

---

package.json
src/index.d.ts

Just like final-form/final-form#39 🙂

Add flow & TypeScript files to Prettier

---

README.md
src/Field.js
src/Field.test.js
src/ReactFinalForm.test.js
src/index.d.ts
src/types.js.flow

Enhances #74. Fixes #45. Fixes #75.

Added documentation for parse/format & killed normalize

---

src/index.d.ts

Fix parse and format TS defs (as not required)

---

README.md
src/ReactFinalForm.js
src/ReactFinalForm.test.js

See discussion here : https://github.com/final-form/react-final-form/issues/83

Make event parameter optional on handleSubmit

---

src/index.d.ts

Added 'batch' and 'mutators' definitions to FormRenderProps

Add 'batch' and 'mutators' TS definitions

---

src/index.d.ts

Reflecting the signature of JS implementation.

Make event optional in TS handleSubmit definition

---

src/Field.js
src/Field.test.js
src/getValue.js
src/getValue.test.js

Enabled checkboxes with value props to maintain array values

---

README.md
src/FormSpy.js
src/FormSpy.test.js
src/index.d.ts
src/types.js.flow

Provided Form API to FormSpy

---

package-lock.json
package.json
src/Field.js
src/ReactFinalForm.js
src/index.js

Adjusted for breaking change in [🏁 Final Form v4.0](https://github.com/final-form/final-form/releases/tag/v4.0.0).

Final Form v4.0 compatibility

---

package.json
src/Field.js
src/getValue.js
src/getValue.test.js
src/index.js

Fixed checkbox bug

---

package-lock.json
package.json
src/Field.js
src/Field.test.js

Removed warning about radio buttons

---

.gitignore
package-lock.json
package-scripts.js
package.json
src/FormSpy.d.test.tsx
src/ReactFinalForm.d.test.tsx
tsconfig.json
tslint.json

Depends on https://github.com/final-form/final-form/pull/66
Closes #125 
Closes #108 
Adds typescript tests to validate common usage.

[typescript] introduce typescript tests

---

src/index.d.ts
src/types.js.flow

[TS/Flow] Adding dirtySinceLastSubmit on FieldRenderProps

---

README.md

I wish Material-UI was that small!

2.9k gzipped + link

---

README.md

Use jsx block for better code highlighting

---

src/ReactFinalForm.js

Fixed React Native event.preventDefault error

---

README.md

Official wording of Material-UI

---

src/ReactFinalForm.js
src/ReactFinalForm.test.js

Fixed bug with postmount updates

---

src/index.d.ts

Change FieldRenderProps['meta']['initial'] to any

---

rollup.config.js

no actual change now, just preventive measure in case u add some deps in the future

Generate externals dynamically from pkg.json

---

.babelrc
rollup.config.js

Use babel loose mode

---

src/types.js.flow

fix handleSubmit flowtype

---

src/FormSpy.js
src/FormSpy.test.js
src/ReactFinalForm.js
src/ReactFinalForm.test.js
src/isSyntheticEvent.js

Ignored React SyntheticEvents on reset calls

---

README.md
package.json
src/Field.js
src/Field.test.js
src/index.d.ts
src/types.js.flow

Added formatOnBlur prop

---

src/types.js.flow

Resolve #282 
@erikras I found easiest way to fix it :)

Fix component prop type conflict

---

README.md

Clarify value FieldProp applicability in docs

---

README.md
package.json
src/ReactFinalForm.js
src/ReactFinalForm.test.js
src/index.d.ts
src/types.js.flow

Fixes #335, solution proposed here: https://github.com/final-form/react-final-form/issues/335#issuecomment-42553411

Added initialValuesEqual predicate prop to Form

---

src/FormSpy.d.test.tsx
src/ReactFinalForm.d.test.tsx

Will this work? Will the PR evaluation bot thingy work? Let's find out!

Attempt to fix LGTM alerts

---

README.md

Update fieldprops documentation

---

package.json
rollup.config.js

Please correct me if I am wrong, but they don't seem to be used anywhere or required for any dependencies.

Remove `prop-types`.

---

README.md

I think this is a correction. If it is not, please reject.

Update readme that warnings do not prevent submit

---

src/Field.test.js
src/ReactFinalForm.js
src/useField.js

Fix type prop passing

---

typescript/FormSpy.test.tsx
typescript/ReactFinalForm.test.tsx
typescript/index.d.ts

Adjust TypeScript definitions to match v5 of the lib.

Adjust TypeScript definitions

---

typescript/index.d.ts
typescript/useFormState.test.tsx

Tweak useFormState TS types

---

src/ReactFinalForm.js
src/ReactFinalForm.test.js

This is the proper fix for #487 and #492. Reverts #495.

Fix form rerender bug

---

README.md
src/Field.test.js
src/renderComponent.test.js
src/useField.js

No rerender on validateFields change

---

src/index.js.flow

Fixes #500. Not sure what happened to removed them. 🤷‍♂️ Sorry! 🙏

Added back flow types that got removed

---

README.md

Hello! Thank you for the great library!
I've fixed broken link to the final-form initialValue section.

fix broken link to initialvalue-any doc section

---

src/Field.test.js
src/useField.js

Pass through multiple value to custom components

---

src/FormSpy.test.js
src/useFormState.js

Fixed FormSpy bug with ignoring changes to onChange

---

examples/debounced-record-level-validation/ErrorWithDelay.js
examples/debounced-record-level-validation/README.md
examples/debounced-record-level-validation/Styles.js
examples/debounced-record-level-validation/index.js
examples/debounced-record-level-validation/package.json

- Migrate one example to the `examples` folder.
I only did one so I can be sure that this is the format you want before I do the others. Let me know if anything needs to change. If not, I'll do all the others similarly and send it as one PR.

Migrate one example

---

docs/examples.md

I have updated the link to work with Material-UI v4.

Remove the version

---

typescript/index.d.ts

Made the comment here: https://github.com/final-form/react-final-form/issues/441#issuecomment-525280614
But then did the PR and saw it was already 'fixed'... but this solution seems better, no?

[ts] FieldInputProps extends AnyObject

---

docs/examples.md

Because now they leads to 404.

Fixed two links to examples

---

docs/examples.md

[docs] add new Material-UI mui-rff components

---

src/ReactFinalForm.js

fix: decorators unsubscribe order

---

docs/migration/redux-form.md

Remove weird comma in redux-form migration guide

---

src/getters.js
src/renderComponent.js
src/useFormState.test.js

Fixes #677 
Also fixes bug found by @onlyann here: https://github.com/final-form/react-final-form/issues/677#issuecomment-555375751

Made lazy state getters enumerable

---

typescript/index.d.ts

Reverts final-form/react-final-form#619

Revert "Fix typescript typings in FieldProps"

---

src/getters.js

Add missing dirtyFieldsSinceLastSubmit to getters

---

docs/types/FormRenderProps.md

This should clarify the handleSubmit's return type to newcomers. Related issue: #675

Added note about the return type of handleSubmit

---

src/Field.test.js
src/useField.js

Submit edge case fix

---

docs/types/FieldProps.md

This is a tiny change that fixes a broken hyperlink

Fix FieldProps → FieldRenderProps link

---

docs/examples.md

only change was to add tslib to the codesandbox dependencies. for some reason it is required now.

[docs] update codesandbox link wrapper components example

---

docs/api/Form.md

Fix typo in focumentation

---

examples/external-submit/index.js

Adds an example of external `<button>` using `form` attribute to submit `<form>`

Add button form attribute example to external submit

---

docs/examples.md

Now that I feel like MUI-RFF is gaining traction and I'm definitely committed to maintaining it, let's remove the link to the old unmaintained project.

[docs] remove unmaintained mui integration project

---

typescript/index.d.ts

I added the type variable "InitialFormValues" like in Final-Form definition

Update Typescript definition to match with Final-Form

---

typescript/index.d.ts

[typescript] apply generic types to params in useFormState declaration

---

docs/faq.md
examples/external-submit/index.js

Programmatic submit does not work in React 17

---

examples/simple/package.json

This should solve the missing dependency error for the simple example on code sandbox

Update package.json with missing dependency.

---

examples/wizard/package.json

This fixes the missing dependency issue on the wizard example.

Update package.json with missing dependency

---

.github/workflows/lock.yml

https://github.com/marketplace/actions/lock-threads

Fix lockbot

---

package.json

Fix final-form version restriction in peerDeps
